[workspace]
resolver = "2"
members = [
    "mdanceio",
    "nanoem",
    "mdanceio-wasm",
]
exclude = [
    "mdance-demo",
]
default-members = ["mdanceio", "nanoem", "mdanceio-wasm"]

[patch.crates-io]
