[package]
name = "nanoemweb-emapp"
version = "0.1.0"
author = ["NAiveD <nice-die@live.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
