[package]
name = "par"
version = "0.1.0"
author = ["NAiveD <nice-die@live.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
