[package]
name = "nanoem"
version = "0.1.0"
authors = ["NAiveD <nice-die@live.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.30"
