[package]
name = "nanoem"
version = "0.1.0"
authors = ["NAiveD <nice-die@live.com>"]
edition = "2021"
description = "MMD Model file and Motion file Parser. "
repository = "https://github.com/ReaNAiveD/mdanceio"
license = "MIT"

[dependencies]
encoding_rs = "0.8.31"
